### ISSUE TITLE
Update consMatFlag in examples 

### ISSUE THREAD

**Issue by mforets** [ONSAS/ONSAS#129]
This is a reminder that in PR https://github.com/ONSAS/ONSAS/pull/128 we updated the use of flag `consMatFlag`,

https://github.com/ONSAS/ONSAS/blob/b5c2821602ef324afba2fc0e849ac9e4329a8da1/sources/elementTetraSolid.m#L84

but some examples still need to be updated wrt that flag.

**Comment by jorgepz** [comment]
This was updated in commit [https://github.com/ONSAS/ONSAS/commit/0eab619b5e93890bdbe29d4303519a354f139bfa](https://github.com/ONSAS/ONSAS/commit/0eab619b5e93890bdbe29d4303519a354f139bfa)
