### ISSUE TITLE
Update storeAndPlotResults.m normal forces and sigmx matrix 

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS#160]
![image](https://user-images.githubusercontent.com/50339940/91604246-b3188d00-e944-11ea-996c-ed9a9cf80b4b.png)

Bug using simple Chain with storeBoolean=1. Neverheless sigmX plot in vtkGeometry function  is working correctly.

**Comment by jorgepz** [comment]
Error running test problem uniformCurvatureCantilever after PR https://github.com/ONSAS/ONSAS/pull/177
```
| TimeSteps progress: 1|                   |  10  |
                        'crossSecsParamsElem' undefined near line 58 column 16
error: called from
    storeAndPlotResults at line 58 column 9
    ONSAS at line 65 column 3
    onsasExample_uniformCurvatureCantilever_test at line 57 column 1
    runTestProblems at line 46 column 3
```

**Comment by mvanzulli** [comment]
Error using TransmissionLineExample

**Comment by jorgepz** [comment]
which is the error message?

**Comment by mvanzulli** [comment]
![image](https://user-images.githubusercontent.com/50339940/92491893-246c0180-f1c9-11ea-84cf-38a7732cbf19.png)

**Comment by mvanzulli** [comment]
![image](https://user-images.githubusercontent.com/50339940/95232362-c25be780-07da-11eb-9ef7-42647bdadf94.png)

Bug using onsasExample_BeamTrussJoint_test script on my branch. The problem occurs when co-exists many element types.

**Comment by mvanzulli** [comment]
https://github.com/ONSAS/ONSAS/pull/188/files I fixed that bug early but any pull request merged into master !

**Comment by mvanzulli** [comment]
Bug ussing beam truss joint.  To fix the problem must delete element params mat

**Comment by mvanzulli** [comment]
Mat Ns using cantilever Pendulum
![image](https://user-images.githubusercontent.com/50339940/106822449-ef6fb800-665d-11eb-8fbe-52fe90d88983.png)
