### ISSUE TITLE
Error vtk plot for circular sections

### ISSUE THREAD

**Issue by mvanzulli** [ONSAS/ONSAS#192]
Using transmission line example. Also can be reproduce runing chain with ciruclar section.
![image](https://user-images.githubusercontent.com/50339940/92524312-45981680-f1f8-11ea-816e-e8a88a6eb525.png)

**Comment by jorgepz** [comment]
![a](https://user-images.githubusercontent.com/42485529/92779625-9afb3180-f378-11ea-8114-854f2c751fed.gif)
