### ISSUE TITLE
fix errors in documentation examples

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS#497]
- [x] fix links to and add figures in spring mass example
- [ ] complete the description of the analytic solution in the beamlinearvibration example
- [x] add figure of the uniform curvature example
- [x] Add computeTangentAero into docs. 
- [x] Fix deployable ring gif in docs
- [x] Fix Ring plane strain

**Comment by jorgepz** [comment]
removed the userload func since it will be changed.

**Comment by santiago-correa-89** [comment]
Hi! Quick question, for point 2 I should work with the master?

**Comment by mvanzulli** [comment]
> Hi! Quick question, for point 2 I should work with a specific PR? or should I need to create a PR for fix this? I will start to work on it.

Exactly, as we discuss you should work in your own branch, open a PR and then request for a member to review it :bookmark_tabs:

**Comment by mvanzulli** [comment]
Hey guys, do you think would be nice to have this example instead of the wind turbine one ? 
![optim](https://user-images.githubusercontent.com/50339940/193476699-dbae5a86-539f-4365-aa97-d49c2af2648e.gif)

**Comment by jorgepz** [comment]
Yes! Would be nice to update the wind turbine example indeed. I would show only one model of deformation and would use a propper factor in the time.

**Comment by santiago-correa-89** [comment]
Hi guys, I found Reference Wind Turbines of NREL this are open researching geometries validates by NREL so I am trying to implement all the geometry now. At the same time I am working in implement a uBEM (unstedy Blade Element Method) recommended by Martin Draper as part of MFC course. I will upload some results soon.

**Comment by jorgepz** [comment]
awesome! do not hesitate in contacting us via email or gitter to discuss, or even opening a draft PR a showing what you are working on...
