### ISSUE TITLE
add variable lengths of steps in arc-length method

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS#530]
- [x] add feature
 - [x] add use of it in some test example, for instance... add a variable length step as another case in https://github.com/ONSAS/ONSAS.m/blob/master/examples/staticVonMisesTruss/onsasExample_staticVonMisesTruss.m
 - [ ] include in the creatingmodels docs

**Comment by jorgepz** [comment]
first sub task done in https://github.com/ONSAS/ONSAS.m/pull/539

**Comment by JoaquinViera** [comment]
@jorgepz you mean the actual implemented version where the user speecifies the step or the method proposed in Jirasek?

**Comment by jorgepz** [comment]
i mean that in https://github.com/ONSAS/ONSAS.m/pull/539 the feature of setting the step was already added.
then, in this issue we only need to add a test to show that this actually works
then in some future... we could add the jirasek modified version of arc length, it would be awesome!

**Comment by jorgepz** [comment]
i updated the description to be more explicit

**Comment by JoaquinViera** [comment]
@jorgepz i noted that the Von Mises example is not in folder pointed here. Also, there are two folders that refers to the static von mises truss. Which one shall have the example?

**Comment by jorgepz** [comment]
Indeed, it changed. This is the current route https://github.com/ONSAS/ONSAS.m/blob/master/examples/static_von_mises_truss/static_von_mises_truss.m

**Comment by jorgepz** [comment]
reopen since missing in docs yet
