### ISSUE TITLE
add matFint test

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS#558]
- [x] add test for internal forces in linear frame element
 - [ ] corotational element
 - [ ] truss element
 - [ ] plate element

**Comment by mvanzulli** [comment]
This is not working by the moment, at least is not equals to the aerodynamic forces and also the reaction forces in `linearAerodynamics.m` example. However we can add a matForces which extracts Fint, Fext, Faero and Fine optionally for each elements in a cell.
