### ISSUE TITLE
add jirasek option to arc length

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS#650]
- [x] add code
 - [x] add test such as vonmises
 - [x] add to docs

**Comment by jorgepz** [comment]
first lines of code added by @JoaquinViera in #646

**Comment by JoaquinViera** [comment]
Added jirasek to current von mises example in PR #652

**Comment by jorgepz** [comment]
I suggest closing this after adding the jirasek option description to the docs...
