### ISSUE TITLE
fix docs inconsistencies

### ISSUE THREAD

**Issue by jorgepz** [ONSAS/ONSAS#704]
- [x] geometricNonLinearAero is a field in analysisSettings in the exmples and in the docs is part of the elements struct. fix that
 - [ ] imposdisdofs etc are not cells currently...fix

**Comment by mvanzulli** [comment]
I can try to address this, can you expand on what you mean about `imposdisdofs etc are not cells currently...fix` ? Thanks

**Comment by jorgepz** [comment]
Yes. That the docs say it is a cell while it is a field that contains a vector. 

```Matlab
vectorboundaryConds(1).imposDispDofs = [ 1 3 5 ]
```

Thanks for working on this!

**Comment by mvanzulli** [comment]
Regarding the numerical aerodynamic params I suggest to deprecate that field and define only aero stiff boolean also in analysis settings struct. Gauss num points can be hardcoded in the function as a variable. WDYT?

**Comment by jorgepz** [comment]
with @santiago-correa-89 we've been doing some tests changing the number of gauss points, so I suggest not hardcoding that.

probably the three parameters can be combined in one cell in a field of the analysissettings struct.  just moving the aeroNumericalParams cell from elements to analysis settings.

keep in mind that this should be considered also in https://github.com/ONSAS/ONSAS/blob/master/src/utils/checkONSASFields.m and https://github.com/ONSAS/ONSAS/blob/master/src/utils/setDefaults.m

**Comment by mvanzulli** [comment]
Fair enough, will group them in a unique cell. Maybe the downside is that we will not be able to change these paramours element-wise. Probably is not big deal and is a very unlikely use case.

**Comment by jorgepz** [comment]
yes. I think it'd be very rare that a user would want to change the GIPs of the tangent stiffness strategy for different elements... for the sake of simplicity we can loose that use case.

**Comment by jorgepz** [comment]
I marked the fist sub-task, done in https://github.com/ONSAS/ONSAS/pull/710, as done
